spring:
  application:
    name: notification-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        enabled: false
      config:
        enabled: false
        defaultContext: application
        data-key: data
      enabled: false
  config:
    import: "optional:consul:"

logging:
  level:
    com.alex.bank.notification: INFO
    root: WARN
  #file:
    #name: ${APP_DIR_NOTIF:/home/alexlakers}/${spring.application.name}/app.log

server:
  port: ${APP_PORT_NOTIF:8086}