spring:
  application:
    name: notification-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
          jwk-set-uri: http://localhost:8080/realms/bank-realm/protocol/openid-connect/certs

logging:
  level:
    root: WARN
    com.alex.bank.notification: INFO
  file:
    name: ${NOTIFICATION_STORAGE_DIR:/home/alexlakers/storage-notification-service}/app.log

server:
  port: 8086