spring:

  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_NOTIFICATION:localhost}:${DB_PORT_NOTIFICATION:5436}/${DB_NAME_NOTIFICATION:notification_repository}
    username: ${DB_USER_NOTIFICATION:notificationuser}
    password: ${DB_PASS_NOTIFICATION:notificationpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: ${CONSUMER_GROUP_ID:notification-handlers-v2}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        enable.auto.commit: false
        # Real deserializator
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # Settings JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.alex.bank.common.dto.notification.NotificationRequest
        # My custom function for error handling
        spring.deserializer.value.function: com.alex.bank.notification.service.NotificationErrorProvider
        # Profit
        fetch.min.bytes: ${CONSUMER_FETCH_MIN_BYTES:16384}
        fetch.max.wait.ms: ${CONSUMER_FETCH_MAX_WAIT_MS:500}
        max.poll.records: ${CONSUMER_MAX_POOL_RECORDS:100}
        # Timeouts
        session.timeout.ms: ${CONSUMER_SESSION_TIMEOUT_MS:30000}
        heartbeat.interval.ms: ${CONSUMER_HEARTBEAT_INTERVAL_MS:10000}
        max.poll.interval.ms: ${CONSUMER_MAX_POLL_INTERVAL_MS:300000}



  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://keycloak:8080}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_EXTERNAL_URL:http://keycloak:8080}/realms/bank-realm/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        enabled: false
      config:
        enabled: false
        defaultContext: application
        data-key: data
      enabled: false
  config:
    import: "optional:consul:"

logging:
  level:
    com.alex.bank.notification.service: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    com.fasterxml.jackson: DEBUG
    root: WARN
    #file:
    #name: ${APP_DIR_NOTIF:/home/alexlakers}/${spring.application.name}/app.log
management:
  endpoint:
    health:
      probes:
        enabled: true

  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 0

  metrics:
    tags:
      application: ${spring.application.name}

  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
server:
  port: ${APP_PORT_NOTIF:8086}