#Default values for transfer-service
replicaCount: 1

image:
  repository: local/transfer
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

database:
  host: "{{ .Release.Name }}-postgres-stateful-0.{{ .Release.Name }}-postgres-stateful.{{ .Release.Namespace }}.svc.cluster.local"
  port: 5432
  name: transferdb
  user: postgres
  password: ""

keycloak:
  host: "{{ .Release.Name }}-keycloak"
  port: 8080
  realm: bank-realm
  clientId: transfer-service
  clientSecret: ""

services:
  notificationServiceUrl: "http://{{ .Release.Name }}-notification-service:8086"
  accountServiceUrl: "http://{{ .Release.Name }}-account-service:8082"
  
producer:
  retries: 3
  batchSize: 16384B
  bufferMemory: 33554432B
  lingerMs: 0
  deliveryTimeoutMs: 120000
  requestTimeoutMs: 30000
  maxInFlightRequestsPerConnection: 5

servicePort: 8085

keycloakExternalUrl: "http://192.168.49.2:31080"
kafkaUrl: ""

resources: {}
