services:
  consul:
    image: consul:1.15.4
    command: ["agent", "-dev", "-client=0.0.0.0"]
    ports:
      - "${CONSUL_HOST_PORT}:${CONSUL_PORT}"
    restart: always
    networks:
      backend-net:

  account-db:
    image: postgres:17.0
    ports:
      - "${DB_HOST_PORT_ACCOUNT}:${DB_PORT_ACCOUNT}"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_ACCOUNT}
      - POSTGRES_PASSWORD=${DB_PASS_ACCOUNT}
      - POSTGRES_DB=${DB_NAME_ACCOUNT}
    volumes:
      - db-data-account:/var/lib/postgresql/data
    networks:
      backend-net:

  cash-db:
    image: postgres:17.0
    ports:
      - "${DB_HOST_PORT_CASH}:${DB_PORT_CASH}"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_CASH}
      - POSTGRES_PASSWORD=${DB_PASS_CASH}
      - POSTGRES_DB=${DB_NAME_CASH}
    volumes:
      - db-data-cash:/var/lib/postgresql/data
    networks:
      backend-net:

  transfer-db:
    image: postgres:17.0
    ports:
      - "${DB_HOST_PORT_TRANSFER}:${DB_PORT_TRANSFER}"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_TRANSFER}
      - POSTGRES_PASSWORD=${DB_PASS_TRANSFER}
      - POSTGRES_DB=${DB_NAME_TRANSFER}
    volumes:
      - db-data-transfer:/var/lib/postgresql/data
    networks:
      backend-net:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_LOGIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}
      - KC_HOSTNAME=${KEYCLOAK_HOST}
      - KC_HOSTNAME_ALIASES=${KEYCLOAK_HOST_ALIASES}
    ports:
      - "${KEYCLOAK_HOST_PORT}:${KEYCLOAK_PORT}"
    restart: always
    command:
      - start-dev
      - --http-port=${KEYCLOAK_PORT}
    networks:
      backend-net:
        aliases:
          - keycloak

volumes:
  db-data-account:
  db-data-cash:
  db-data-transfer:

networks:
  backend-net: