spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm/protocol/openid-connect/certs


  cloud:
    loadbalancer:
      enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        enabled: false
      config:
        enabled: false
        defaultContext: application
        data-key: data
      enabled: false


    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                  - Path=/accounts/**
              filters:
              - RewritePath=/(?<path>.*), /api/v1/$\{path}
              - name: JwtTokenRelay

            - id: cash-service
              uri: lb://cash-service
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/(?<path>.*), /api/v1/$\{path}
                - name: JwtTokenRelay

            - id: transfer-service
              uri: lb://transfer-service
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/(?<path>.*), /api/v1/$\{path}
                - name: JwtTokenRelay



  config:
    import: "optional:consul:"

logging:
  level:
    com.alex.bank.gateway: INFO
    root: WARN

  file:
    name: ${APP_DIR_GATEWAY:/home/alexlakers}/${spring.application.name}/app.log

server:
  port: ${APP_PORT_GATEWAY:8888}