{
 "title": "bank-business-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(cash_operation_failures_total,username)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Business-metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transfer-service: transfer's failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(receiver) (transfer_failures_total{sender=~\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification-service: failures events handling",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (notification_failures_total{username=\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash-service: failed operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(action) (cash_operation_failures_total{username=~\"$username\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}