{
 "title": "bank-http-metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency p95 per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, service) (rate(http_server_requests_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (rate(http_server_requests_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Errors per Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(http_server_requests_seconds_count{status=~\"5..\",service=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Error per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service) (increase(http_server_requests_seconds_count{status=~\"4..\",service=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}