spring:
  application:
    name: cash-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_CASH:localhost}:${DB_PORT_CASH:5434}/${DB_NAME_CASH:cash_repository}
    username: ${DB_USER_CASH:cashuser}
    password: ${DB_PASS_CASH:cashpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm/protocol/openid-connect/certs
      client:
        registration:
          cash-service:
            provider: keycloak
            client-id: ${OAUTH2_CLIENT_ID_CASH}
            client-secret: ${OAUTH2_SECRET_CASH}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            #issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm
             issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8080}/realms/bank-realm

  cloud:
    loadbalancer:
      enabled: false
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        enabled: false
      config:
        enabled: false
        defaultContext: application
        data-key: data
      enabled: false
  config:
    import: "optional:consul:"

cash:
  notification-service:
    baseUrl: ${NOTIFICATION_SERVICE_URL:http://notification-service}
  account-service:
    baseUrl: ${ACCOUNT_SERVICE_URL:http://account-service}

logging:
  level:
    com.alex.bank.cash: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.security.oauth2.client: DEBUG
  file:
    name: ${APP_DIR_CASH:/home/alexlakers}/${spring.application.name}/app.log

resilience4j:
  circuitbreaker:
    instances:
      circuit-account-service:
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 4
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
        failure-rate-threshold: 50
        sliding-window-type: count_based
        minimum-number-of-calls: 8

  retry:
    instances:
      retry-account-service:
        wait-duration: 1s
        max-attempts: 4
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
server:
  port: ${APP_PORT_CASH:8084}