server:
  port: 8083

spring:
  application:
    name: bank-ui

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: http://localhost:8083/login/oauth2/code/keycloak
            provider: keycloak
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
      config:
        enabled: true
        defaultContext: application
        data-key: data
  config:
    import: "consul:"

logging:
  level:
    com.alex.bank.ui: INFO
    root: WARN
  file:
    name: ${APP_DIR:/home/alexlakers}/${spring.application.name}/app.log

