apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}-config
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  DB_HOST_TRANSFER: {{ tpl .Values.database.host $ }}
  DB_PORT_TRANSFER: {{ .Values.database.port | quote }}
  DB_NAME_TRANSFER: {{ .Values.database.name }}
  DB_USER_TRANSFER: {{ .Values.database.user }}

  KEYCLOAK_HOST: {{ tpl .Values.keycloak.host $ }}
  KEYCLOAK_PORT: {{ .Values.keycloak.port | quote }}
  OAUTH2_CLIENT_ID_TRANSFER: {{ .Values.keycloak.clientId }}

  NOTIFICATION_SERVICE_URL: {{ tpl .Values.services.notificationServiceUrl $ }}
  ACCOUNT_SERVICE_URL: {{ tpl .Values.services.accountServiceUrl $ }}

  APP_PORT_TRANSFER: {{ .Values.service.port | quote }}

  KEYCLOAK_EXTERNAL_URL: {{ .Values.keycloakExternalUrl }}
  KAFKA_URL: {{ coalesce .Values.kafkaUrl .Values.global.kafkaUrl "kafka-broker:9092" | quote }}
    # Producer
  PRODUCER_RETRIES: {{ .Values.producer.retries | quote }}
  PRODUCER_BATCH_SIZE: {{ .Values.producer.batchSize | quote }}
  PRODUCER_BUFFER_MEMORY: {{ .Values.producer.bufferMemory | quote }}
  PRODUCER_LINGER_MS: {{ .Values.producer.lingerMs | quote }}
  PRODUCER_DELIVERY_TIMEOUT_MS: {{ .Values.producer.deliveryTimeoutMs | quote }}
  PRODUCER_REQUEST_TIMEOUT_MS: {{ .Values.producer.requestTimeoutMs | quote }}
  PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: {{ .Values.producer.maxInFlightRequestsPerConnection | quote }}
