apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-service.fullname" . }}-secrets
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASS_TRANSFER: {{ .Values.database.password | b64enc | quote }}
  OAUTH2_SECRET_TRANSFER: {{ .Values.keycloak.clientSecret | b64enc | quote }}
