#Default Values for notification-service
replicaCount: 1

image:
  repository: local/notification
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

database:
  host: "{{ .Release.Name }}-postgres-stateful-0.{{ .Release.Name }}-postgres-stateful.{{ .Release.Namespace }}.svc.cluster.local"
  port: 5432
  name: notificationdb
  user: postgres
  password: ""

service:
  port: 8086

consumer:
  groupId: "notification-handlers"
  fetchMinBytes: 16384
  fetchMaxWaitMs: 500
  maxPollRecords: 100
  sessionTimeoutMs: 30000
  heartbeatIntervalMs: 10000
  maxPollIntervalMs: 300000

keycloakExternalUrl: "http://192.168.49.2:31080"
kafkaUrl: ""

logLevel: INFO

resources: {}
