spring:
  application:
    name: cash-service
  datasource:
    url: jdbc:postgresql://${TRANSFER_DB_HOST:localhost}:${TRANSFER_DB_HOST_PORT:5435}/${TRANSFER_DB_NAME:transfer_repository}
    username: ${CASH_DB_USER:transferuser}
    password: ${CASH_DB_PASS:transferpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

      client:
        registration:
          cash-service:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
      config:
        enabled: true
        defaultContext: application
        data-key: data
  config:
    import: "consul:"

transfer:
  notification-service:
    baseUrl: http://notification-service
  account-service:
    baseUrl: http://account-service

logging:
  level:
    com.alex.bank.transfer: INFO
    root: WARN
  file:
    name: ${APP_DIR:/home/alexlakers}/${spring.application.name}/app.log

server:
  port: 8085