spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_TRANSFER:localhost}:${DB_PORT_TRANSFER:5435}/${DB_NAME_TRANSFER:transfer_repository}
    username: ${DB_USER_TRANSFER:transferuser}
    password: ${DB_PASS_TRANSFER:transferpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: ${OAUTH2_CLIENT_ID_TRANSFER}
            client-secret: ${OAUTH2_SECRET_TRANSFER}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
      config:
        enabled: true
        defaultContext: application
        data-key: data
  config:
    import: "optional:consul:"

transfer:
  notification-service:
    baseUrl: ${NOTIFICATION_SERVICE_URL:http://notification-service}
  account-service:
    baseUrl: ${ACCOUNT_SERVICE_URL:http://account-service}

logging:
  level:
    com.alex.bank.transfer: INFO
    root: WARN
  file:
    name: ${APP_DIR_TRANSFER:/home/alexlakers}/${spring.application.name}/app.log

server:
  port: ${APP_PORT_TRANSFER:8085}