apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: api-gateway
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.keycloakExternalUrl }}/realms/bank-realm
              jwk-set-uri: {{ .Values.keycloakExternalUrl }}/realms/bank-realm/protocol/openid-connect/certs
      cloud:
        gateway:
          routes:
            - id: account-service
              uri: {{ tpl .Values.accountServiceUrl $ }}
              predicates:
                - Path=/accounts/**
              filters:
                - RewritePath=/(?<path>.*), /api/v1/$\{path}
                - name: JwtTokenRelay
            - id: cash-service
              uri: {{ tpl .Values.cashServiceUrl $ }}
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/(?<path>.*), /api/v1/$\{path}
                - name: JwtTokenRelay
            - id: transfer-service
              uri: {{ tpl .Values.transferServiceUrl $ }}
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/(?<path>.*), /api/v1/$\{path}
                - name: JwtTokenRelay

    logging:
      level:
        com.alex.bank.gateway: INFO
        root: WARN
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web.server: DEBUG
        org.springframework.security: DEBUG

    management:
      tracing:
        sampling:
          probability: 1.0
      zipkin:
        tracing:
          endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}
      endpoint:
        health:
          probes:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health

    server:
      port: {{ .Values.service.port }}

  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://{{ coalesce .Values.zipkinUrl .Values.global.zipkinUrl "zipkin:9411" }}/api/v2/spans
