apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}-config
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
data:
  DB_HOST_NOTIFICATION: {{ tpl .Values.database.host $ }}
  DB_PORT_NOTIFICATION: {{ .Values.database.port | quote }}
  DB_NAME_NOTIFICATION: {{ .Values.database.name }}
  DB_USER_NOTIFICATION: {{ .Values.database.user }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.keycloakExternalUrl | quote }}
  APP_PORT_NOTIF: {{ .Values.service.port | quote }}
  KAFKA_URL: {{ coalesce .Values.kafkaUrl .Values.global.kafkaUrl "kafka-broker:9092" | quote }}
