# General
replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""


ingress:
  enabled: true
  className: nginx
  host: ""
  annotations: {}

postgres-stateful:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: ""
  nameOverride: ""
  fullnameOverride: ""
  postgresPassword: ""
  databases:
    - accountdb
    - transferdb
    - cashdb
  storage:
    size: 100Mi
    storageClassName: ""

keycloak:
  enabled: true
  admin:
    login: admin
    password: admin123
  realmImport:
    enabled: true
    filename: realm-export.json
  #service:
    #type: NodePort
    #nodePort: 31080

account-service:
  enabled: true
  image:
    repository: account
    tag: latest
  keycloak:
    clientSecret: ""
  service:
    port: 8082
  keycloakExternalUrl: "http://192.168.49.2:31080"
  services:
    notificationServiceUrl: "http://{{ .Release.Name }}-notification-service:8086"

transfer-service:
  enabled: true
  image:
    repository: transfer
    tag: latest
    pullPolicy: IfNotPresent
  database:
    host: "{{ .Release.Name }}-postgres-stateful-0.{{ .Release.Name }}-postgres-stateful.{{ .Release.Namespace }}.svc.cluster.local"
    port: 5432
    name: transferdb
    user: postgres
    password: ""
  keycloak:
    host: "{{ .Release.Name }}-keycloak"
    port: 8080
    realm: bank-realm
    clientId: transfer-service
    clientSecret: ""
  service:
    port: 8085
  keycloakExternalUrl: "http://192.168.49.2:31080"
  services:
    notificationServiceUrl: "http://{{ .Release.Name }}-notification-service:8086"
    accountServiceUrl: "http://{{ .Release.Name }}-account-service:8082"

cash-service:
  enabled: true
  image:
    repository: cash
    tag: latest
  keycloak:
    clientSecret: ""
  service:
    port: 8084
  keycloakExternalUrl: "http://192.168.49.2:31080"
  services:
    notificationServiceUrl: "http://{{ .Release.Name }}-notification-service:8086"
    accountServiceUrl: "http://{{ .Release.Name }}-account-service:8082"

notification-service:
  enabled: true
  image:
    repository: notification
    tag: latest
  keycloakExternalUrl: "http://192.168.49.2:31080"
  service:
    port: 8086

bank-ui:
  enabled: true
  image:
    repository: ui
    tag: latest
  keycloak:
    clientSecret: ""
  service:
    port: 8083
  keycloakExternalUrl: "http://192.168.49.2:31080"
  gatewayUrl: "http://{{ .Release.Name }}-api-gateway:8888"
  appBaseUrl: "http://192.168.49.2:30690"
  accountServiceUrl: "http://{{ .Release.Name }}-account-service:8082"
  transferServiceUrl: "http://{{ .Release.Name }}-transfer-service:8085"
  cashServiceUrl: "http://{{ .Release.Name }}-cash-service:8084"

api-gateway:
  enabled: true
  replicaCount: 1
  image:
    repository: gateway
    tag: latest
  service:
    #type: ClusterIP
    port: 8888
  keycloakExternalUrl: "http://192.168.49.2:31080"
  accountServiceUrl: "http://{{ .Release.Name }}-account-service:8082"
  cashServiceUrl: "http://{{ .Release.Name }}-cash-service:8084"
  transferServiceUrl: "http://{{ .Release.Name }}-transfer-service:8085"
