apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-stateful.fullname" . }}
  labels:
    {{- include "postgres-stateful.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}
