apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-stateful.fullname" . }}
  labels:
    {{- include "postgres-stateful.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres-stateful.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-stateful.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-stateful.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres-stateful.fullname" . }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    until pg_isready -U postgres; do
                      echo "Waiting for PostgreSQL to be ready..."
                      sleep 2
                    done
                    for db in {{ .Values.databases | join " " }}; do
                      echo "Checking database: $db"
                      psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$db'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE $db"
                    done
      volumes: []  # теперь volumes пуст (можно удалить эту строку или оставить)
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
