apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}-config
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  DB_HOST_ACCOUNT: {{ tpl .Values.database.host $ }}
  DB_PORT_ACCOUNT: {{ .Values.database.port | quote }}
  DB_NAME_ACCOUNT: {{ .Values.database.name }}
  DB_USER_ACCOUNT: {{ .Values.database.user }}
  KEYCLOAK_HOST: {{ tpl .Values.keycloak.host $ }}
  KEYCLOAK_PORT: {{ .Values.keycloak.port | quote }}
  OAUTH2_CLIENT_ID_ACCOUNT: {{ .Values.keycloak.clientId }}
  NOTIFICATION_SERVICE_URL: {{ tpl .Values.services.notificationServiceUrl $ }}
  APP_PORT_ACCOUNT: {{ .Values.servicePort | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.keycloakExternalUrl }}
  KAFKA_URL: {{ coalesce .Values.kafkaUrl .Values.global.kafkaUrl "kafka-broker:9092" | quote }}
  ZIPKIN_URL: {{ coalesce .Values.zipkinUrl .Values.global.zipkinUrl "zipkin:9411" | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ coalesce .Values.zipkinUrl .Values.global.zipkinUrl "http://zipkin:9411" }}/api/v2/spans
  # Producer
  PRODUCER_RETRIES: {{ .Values.producer.retries | quote }}
  PRODUCER_BATCH_SIZE: {{ .Values.producer.batchSize | quote }}
  PRODUCER_BUFFER_MEMORY: {{ .Values.producer.bufferMemory | quote }}
  PRODUCER_LINGER_MS: {{ .Values.producer.lingerMs | quote }}
  PRODUCER_DELIVERY_TIMEOUT_MS: {{ .Values.producer.deliveryTimeoutMs | quote }}
  PRODUCER_REQUEST_TIMEOUT_MS: {{ .Values.producer.requestTimeoutMs | quote }}
  PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: {{ .Values.producer.maxInFlightRequestsPerConnection | quote }}
