#Default Values for api-gateway
replicaCount: 1

image:
  repository: local/gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8888

keycloakExternalUrl: "http://192.168.49.2:31080"

accountServiceUrl: "http://my-bank-account-service:8082"
cashServiceUrl: "http://my-bank-cash-service:8084"
transferServiceUrl: "http://my-bank-transfer-service:8085"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
