spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_HOST_PORT:5433}/${DB_NAME:account_repository}
    username: ${DB_USER:accountuser}
    password: ${DB_PASS:accountpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    contexts: dev
    change-log: db/changelog/db.changelog-master.xml

  security:
    oauth2:
      client:
        registration:
          account-service:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/bank-realm

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
      config:
        enabled: true
        defaultContext: application
        data-key: data
  config:
    import: "consul:"

logging:
  level:
    com.alex.bank.account: INFO
    root: WARN
  file:
    name: ${APP_DIR:/home/alexlakers}/${spring.application.name}/app.log

accounts:
  notification-service:
    base-url: http://notification-service

server:
  port: 8082