apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}-config
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
data:
  DB_HOST_CASH: {{ tpl .Values.database.host $ }}
  DB_PORT_CASH: {{ .Values.database.port | quote }}
  DB_NAME_CASH: {{ .Values.database.name }}
  DB_USER_CASH: {{ .Values.database.user }}

  KEYCLOAK_HOST: {{ tpl .Values.keycloak.host $ }}
  KEYCLOAK_PORT: {{ .Values.keycloak.port | quote }}
  OAUTH2_CLIENT_ID_CASH: {{ .Values.keycloak.clientId }}

  NOTIFICATION_SERVICE_URL: {{ tpl .Values.services.notificationServiceUrl $ }}
  ACCOUNT_SERVICE_URL: {{ tpl .Values.services.accountServiceUrl $ }}

  APP_PORT_CASH: {{ .Values.servicePort | quote }}

  KEYCLOAK_EXTERNAL_URL: {{ .Values.keycloakExternalUrl }}
  KAFKA_URL: {{ coalesce .Values.kafkaUrl .Values.global.kafkaUrl "kafka-broker:9092" | quote }}
