apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bank-ui.fullname" . }}-secrets
  labels:
    {{- include "bank-ui.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH2_SECRET_UI: {{ .Values.keycloak.clientSecret | b64enc | quote }}
