apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bank-ui.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus-stack
    {{- include "bank-ui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      {{- include "bank-ui.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 45s
